build: *
	@echo "Building FrontendGcer..."
	npm install && npm run build
	@echo "FrontendGcer build complete."
dev:
	@echo "Starting FrontendGcer..."
	npm install && npm run dev
	@echo "FrontendGcer started."
start:
	serve -s dist
